const directory=[
    {
      icon: "mdi-book-open-page-variant",
      "icon-alt": "mdi-chevron-down",
      text: "导言",
      model: false,
      children: [
        { id:"0_Introduction",text: "为什么是Web而不是Unity？" },
        { id:"1_WhyModernJavaScript",text: "为什么使用现代JavaScript" },
        { id:"2_HowtoUsethisBook",text: "如何使用这本书？" },
      ],
    },
    {
      icon: "mdi-speedometer",
      text: "入门",
      model: false,
      children: [
        { id:"3_GettingStarted",text: "创建新文件夹"},
        {  id:"4_DevelopmentServer",text: "开发服务器" },
        {  id:"5_Createanindex",text: "创建index.html" },
        {  id:"6_CreatetheEntryPoint",text: "创建入口点" },
        {  id:"7_LetisGoLive",text: "让我们去直播吧" },
        {  id:"8_Troubleshooting",text: "排除故障" },
        {  id:"9_ModernJavaScript",text: "现代JavaScript" },
        {  id:"10_UsingModules",text: "使用模块"},
        { id:"11_VSCodeIntelliSense",text: "VS代码IntelliSense" },
        {  id:"12_ReadyPlayerOne",text: "准备好，第一个游戏" },
      ],
    },
    {
      icon: "mdi-numeric-1-box-multiple",
      text: "设置游戏",
      model: false,
      children: [
        { id:"13_CreatingaPhaserGame", text: "创建Phaser游戏" },
        { id:"14_CreatingAGameScene",text: "创建游戏场景" },
        { id:"15_DetourintoClasses",text: "绕道类" },
        { id:"16_StartingTheGameScene",text: "开始游戏场景" },
        { id:"17_PreloadaBackground",text: "预加载游戏背景" },
        { id:"18_CreatingTheBackground",text: "创造游戏背景" },
      ],
    },
    {
      icon: "mdi-numeric-2-box-multiple",
      text: "创建平台",
      model: false,
      children: [
        { id:"19_AddArcadePhysics",text: "添加街机物理"},
        { id:"20_AddAPhysicsEnabledPlatform",text: "添加启用物理的平台" },
        { id:"21_AddingMultiplePlatforms",text: "添加多个平台" },
      ],
    },
    {
      icon: "mdi-numeric-3-box-multiple",
      text: "创建播放器",
      model: false,
      children: [
        { id:"22_AddingCollisions",text: "添加碰撞" },
        { id:"23_UsingClassProperties",text: "使用类属性" },
        { id:"24_LetIsJump",text: "我们跳吧" },
        { id:"25_DetourintoVelocity",text: "绕行速度" },  
        { id:"26_FollowthatRabbit",text: "跟着那只兔子" },
      ],
    },
    {
      icon: "mdi-numeric-4-box-multiple",
      text: "滚动平台",
      model: false,
      children: [{ id:"27_ReuseAndRecycle",text: "重用和回收" }, 
                  { id:"28_KeepTheBackgroundFromScrolling",text: "保持背景滚动" }],
    },
    {
      icon: "mdi-numeric-5-box-multiple",
      text: "左右移动",
      model: false,
      children: [
        { id:"29_HandlingMoveLogic",text: "处理移动逻辑" },
        { id:"30_UsingCameraDeadZones",text: "使用相机死区" },
        { id:"31_HorizontalWrapAround",text: "水平环绕" },
      ],
    },
    {
      icon: "mdi-numeric-6-box-multiple",
      text: "收集胡萝卜",
      model: false,
      children: [
        { id:"32_AddingCarrotsToTheGame",text: "在游戏中加入胡萝卜" },
        { id:"33_CreatePhysicsCarrots",text: "创建一组物理驱动的胡萝卜" },
        { id:"34_CleanUpDetour",text: "清理绕道" },
        { id:"35_PutCarrotsonPlatforms",text: "把胡萝卜放在平台上" },
        { id:"36_LetIsCollectSomeCarrots",text: "让我们收集一些胡萝卜" },
        { id:"37_ReusingCarrots",text: "重用胡萝卜" },
      ],
    },
    {
      icon: "mdi-numeric-7-box-multiple",
      text: "跟踪记分",
      model: false,
      children: [{ id:"38_UpdatingCollected",text: "更新收集的胡萝卜案文" }],
    },
    {
      icon: "mdi-numeric-8-box-multiple",
      text: "处理游戏结束",
      model: false,
      children: [
        { id:"39_GameOverScene",text: "游戏结束场景" },
        { id:"40_AddPlayAgain",text: "重新开始游戏" },
        { id:"41_InitializingScene",text: "初始化场景属性" },
      ],
    },
    {
      icon: "mdi-numeric-9-box-multiple",
      text: "具有跳跃纹理的简单动画",
      model: false,
      children: [{ id:"42_SwitchBackToStand",text: "切切换回原位" },
                 { id:"43_JustOneMoreThing",text: "还有一件事…" }],
    },
  ]

export default directory