const directory=[
    {
      icon: "mdi-book-open-page-variant",
      "icon-alt": "mdi-chevron-down",
      text: "导言",
      model: false,
      children: [
        { id:"0_Introduction",text: "为什么是Web而不是Unity？" },
        { id:"1_WhyModernJavaScript",text: "为什么使用现代JavaScript" },
        { id:"2_HowtoUsethisBook",text: "如何使用这本书" },
      ],
    },
    {
      icon: "mdi-speedometer",
      text: "入门",
      model: false,
      children: [
        { id:"3_GettingStarted",text: "创建新文件夹"},
        {  id:"4_DevelopmentServer",text: "开发服务器" },
        {  id:"5_Createanindex",text: "创建index.html" },
        {  id:"undone",text: "创建入口点" },
        {  id:"undone",text: "让我们去直播吧" },
        {  id:"undone",text: "现代JavaScript" },
        {  id:"undone",text: "使用模块" },
        { id:"undone",text: "VS代码IntelliSense" },
        {  id:"undone",text: "准备好，一号9号选手" },
      ],
    },
    {
      icon: "mdi-numeric-1-box-multiple",
      text: "设置游戏",
      model: false,
      children: [
        { id:"undone", text: "创建相位器游戏" },
        { id:"undone",text: "创建游戏场景" },
        { id:"undone",text: "绕道入班" },
        { id:"undone",text: "开始游戏场景" },
        { id:"undone",text: "预加载背景" },
        { id:"undone",text: "创造背景" },
      ],
    },
    {
      icon: "mdi-numeric-2-box-multiple",
      text: "创建平台",
      model: false,
      children: [
        { id:"undone",text: "添加拱廊物理"},
        { id:"undone",text: "添加物理支持平台" },
        { id:"undone",text: "添加多个平台" },
      ],
    },
    {
      icon: "mdi-numeric-3-box-multiple",
      text: "创建播放器",
      model: false,
      children: [
        { id:"undone",text: "添加碰撞" },
        { id:"undone",text: "使用类属性" },
        { id:"undone",text: "我们跳吧" },
        { id:"undone",text: "我们跳吧" },
        { id:"undone",text: "迂回进入速度" },
        { id:"undone",text: "跟着那只兔子" },
      ],
    },
    {
      icon: "mdi-numeric-4-box-multiple",
      text: "滚动平台",
      model: false,
      children: [{ id:"undone",text: "再利用和再循环" }, 
                  { id:"undone",text: "保持背景滚动" }],
    },
    {
      icon: "mdi-numeric-5-box-multiple",
      text: "左右移动",
      model: false,
      children: [
        { id:"undone",text: "处理移动逻辑" },
        { id:"undone",text: "使用相机死区" },
        { id:"undone",text: "水平环绕" },
      ],
    },
    {
      icon: "mdi-numeric-6-box-multiple",
      text: "收集胡萝卜",
      model: false,
      children: [
        { id:"undone",text: "在游戏中加入胡萝卜" },
        { id:"undone",text: "创建一组物理驱动的胡萝卜" },
        { id:"undone",text: "清理绕道" },
        { id:"undone",text: "把胡萝卜放在平台上" },
        { id:"undone",text: "让我们收集一些胡萝卜" },
        { id:"undone",text: "再利用胡萝卜" },
      ],
    },
    {
      icon: "mdi-numeric-7-box-multiple",
      text: "记分",
      model: false,
      children: [{ id:"undone",text: "更新收集的胡萝卜案文" }],
    },
    {
      icon: "mdi-numeric-8-box-multiple",
      text: "处理游戏超过",
      model: false,
      children: [
        { id:"undone",text: "Scene52上的游戏" },
        { id:"undone",text: "添加再次播放" },
        { id:"undone",text: "初始化场景属性" },
      ],
    },
    {
      icon: "mdi-numeric-9-box-multiple",
      text: "简单的动画与跳转纹理",
      model: false,
      children: [{ id:"undone",text: "切换回Stand" },
                 { id:"undone",text: "还有一件事…" }],
    },
  ]

export default directory